# Generated by Django 4.1.2 on 2022-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price_usd', models.PositiveIntegerField(verbose_name='price usd')),
                ('price_rub', models.PositiveIntegerField(verbose_name='price rub')),
                ('stripe_price', models.CharField(blank=True, default='', max_length=100, verbose_name='price_stripe')),
                ('stripe_id', models.CharField(blank=True, default='', max_length=100, verbose_name='stripe_id')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('payment_at', models.DateTimeField(null=True, verbose_name='payment_at')),
                ('items', models.ManyToManyField(null=True, related_name='order', to='app_items.item', verbose_name='items')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
