# Generated by Django 4.1.2 on 2022-11-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_stripe', '0002_alter_discount_duration'),
        ('app_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='app_stripe.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='app_stripe.taxrate', verbose_name='tax rate'),
        ),
    ]
