# Generated by Django 4.1.2 on 2022-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('duration', models.CharField(choices=[('Once', 'Once'), ('Forever', 'Forever'), ('Repeating', 'Repeating')], default='Forever', max_length=10, verbose_name='duration')),
                ('percent_off', models.DecimalField(decimal_places=1, default=10, max_digits=100, verbose_name='percent off')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('inclusive', models.BooleanField(default=False, verbose_name='inclusive')),
                ('percentage', models.DecimalField(decimal_places=1, default=10, max_digits=100, verbose_name='percentage')),
            ],
        ),
    ]
