# Generated by Django 4.1.2 on 2022-11-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stripe', '0002_alter_discount_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'verbose_name': 'tax rate', 'verbose_name_plural': 'tax rates'},
        ),
    ]
