# Generated by Django 4.1.2 on 2022-11-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stripe', '0003_alter_discount_options_alter_taxrate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='id_in_stripe'),
        ),
    ]
